embeddings {
  tensor_name: "Vowel_vectors_ndim_3:0"
  metadata_path: "meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_6:0"
  metadata_path: "meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_12:0"
  metadata_path: "meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_24:0"
  metadata_path: "meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_36:0"
  metadata_path: "meta.tsv"
}
