embeddings {
  tensor_name: "Vowel_vectors_ndim_3:0"
  metadata_path: "meta/meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_6:0"
  metadata_path: "meta/meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_12:0"
  metadata_path: "meta/meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_24:0"
  metadata_path: "meta/meta.tsv"
}
embeddings {
  tensor_name: "Vowel_vectors_ndim_36:0"
  metadata_path: "meta/meta.tsv"
}
embeddings {
  tensor_name: "VKB0:0"
  metadata_path: "meta/meta_VKB0.tsv"
}
embeddings {
  tensor_name: "KAH0:0"
  metadata_path: "meta/meta_KAH0.tsv"
}
embeddings {
  tensor_name: "DPB0:0"
  metadata_path: "meta/meta_DPB0.tsv"
}
embeddings {
  tensor_name: "BCG1:0"
  metadata_path: "meta/meta_BCG1.tsv"
}
embeddings {
  tensor_name: "JXM0:0"
  metadata_path: "meta/meta_JXM0.tsv"
}
embeddings {
  tensor_name: "WSH0:0"
  metadata_path: "meta/meta_WSH0.tsv"
}
embeddings {
  tensor_name: "CLT0:0"
  metadata_path: "meta/meta_CLT0.tsv"
}
embeddings {
  tensor_name: "AJP0:0"
  metadata_path: "meta/meta_AJP0.tsv"
}
embeddings {
  tensor_name: "MAH0:0"
  metadata_path: "meta/meta_MAH0.tsv"
}
embeddings {
  tensor_name: "JRB0:0"
  metadata_path: "meta/meta_JRB0.tsv"
}
embeddings {
  tensor_name: "ASW0:0"
  metadata_path: "meta/meta_ASW0.tsv"
}
embeddings {
  tensor_name: "RTK0:0"
  metadata_path: "meta/meta_RTK0.tsv"
}
embeddings {
  tensor_name: "LBW0:0"
  metadata_path: "meta/meta_LBW0.tsv"
}
embeddings {
  tensor_name: "SAH1:0"
  metadata_path: "meta/meta_SAH1.tsv"
}
embeddings {
  tensor_name: "LJB0:0"
  metadata_path: "meta/meta_LJB0.tsv"
}
embeddings {
  tensor_name: "LMC0:0"
  metadata_path: "meta/meta_LMC0.tsv"
}
embeddings {
  tensor_name: "CJS0:0"
  metadata_path: "meta/meta_CJS0.tsv"
}
embeddings {
  tensor_name: "APV0:0"
  metadata_path: "meta/meta_APV0.tsv"
}
embeddings {
  tensor_name: "JSJ0:0"
  metadata_path: "meta/meta_JSJ0.tsv"
}
embeddings {
  tensor_name: "KAG0:0"
  metadata_path: "meta/meta_KAG0.tsv"
}
embeddings {
  tensor_name: "JSK0:0"
  metadata_path: "meta/meta_JSK0.tsv"
}
embeddings {
  tensor_name: "JXA0:0"
  metadata_path: "meta/meta_JXA0.tsv"
}
embeddings {
  tensor_name: "DHS0:0"
  metadata_path: "meta/meta_DHS0.tsv"
}
embeddings {
  tensor_name: "CFT0:0"
  metadata_path: "meta/meta_CFT0.tsv"
}
embeddings {
  tensor_name: "JRF0:0"
  metadata_path: "meta/meta_JRF0.tsv"
}
embeddings {
  tensor_name: "CSS0:0"
  metadata_path: "meta/meta_CSS0.tsv"
}
embeddings {
  tensor_name: "WAR0:0"
  metadata_path: "meta/meta_WAR0.tsv"
}
embeddings {
  tensor_name: "DWK0:0"
  metadata_path: "meta/meta_DWK0.tsv"
}
embeddings {
  tensor_name: "NTB0:0"
  metadata_path: "meta/meta_NTB0.tsv"
}
embeddings {
  tensor_name: "BNS0:0"
  metadata_path: "meta/meta_BNS0.tsv"
}
embeddings {
  tensor_name: "AWF0:0"
  metadata_path: "meta/meta_AWF0.tsv"
}
embeddings {
  tensor_name: "SAK0:0"
  metadata_path: "meta/meta_SAK0.tsv"
}
embeddings {
  tensor_name: "BEF0:0"
  metadata_path: "meta/meta_BEF0.tsv"
}
embeddings {
  tensor_name: "GRW0:0"
  metadata_path: "meta/meta_GRW0.tsv"
}
embeddings {
  tensor_name: "DLM0:0"
  metadata_path: "meta/meta_DLM0.tsv"
}
embeddings {
  tensor_name: "WJG0:0"
  metadata_path: "meta/meta_WJG0.tsv"
}
embeddings {
  tensor_name: "MDB1:0"
  metadata_path: "meta/meta_MDB1.tsv"
}
embeddings {
  tensor_name: "DMY0:0"
  metadata_path: "meta/meta_DMY0.tsv"
}
embeddings {
  tensor_name: "CEW0:0"
  metadata_path: "meta/meta_CEW0.tsv"
}
embeddings {
  tensor_name: "DAS1:0"
  metadata_path: "meta/meta_DAS1.tsv"
}
embeddings {
  tensor_name: "DLR0:0"
  metadata_path: "meta/meta_DLR0.tsv"
}
embeddings {
  tensor_name: "BMA1:0"
  metadata_path: "meta/meta_BMA1.tsv"
}
embeddings {
  tensor_name: "SMS1:0"
  metadata_path: "meta/meta_SMS1.tsv"
}
embeddings {
  tensor_name: "CTW0:0"
  metadata_path: "meta/meta_CTW0.tsv"
}
embeddings {
  tensor_name: "GRT0:0"
  metadata_path: "meta/meta_GRT0.tsv"
}
embeddings {
  tensor_name: "TWH0:0"
  metadata_path: "meta/meta_TWH0.tsv"
}
embeddings {
  tensor_name: "DNS0:0"
  metadata_path: "meta/meta_DNS0.tsv"
}
embeddings {
  tensor_name: "CAU0:0"
  metadata_path: "meta/meta_CAU0.tsv"
}
embeddings {
  tensor_name: "PAF0:0"
  metadata_path: "meta/meta_PAF0.tsv"
}
embeddings {
  tensor_name: "RSP0:0"
  metadata_path: "meta/meta_RSP0.tsv"
}
embeddings {
  tensor_name: "DXW0:0"
  metadata_path: "meta/meta_DXW0.tsv"
}
embeddings {
  tensor_name: "WEM0:0"
  metadata_path: "meta/meta_WEM0.tsv"
}
embeddings {
  tensor_name: "DAB0:0"
  metadata_path: "meta/meta_DAB0.tsv"
}
embeddings {
  tensor_name: "KLS1:0"
  metadata_path: "meta/meta_KLS1.tsv"
}
embeddings {
  tensor_name: "MPM0:0"
  metadata_path: "meta/meta_MPM0.tsv"
}
embeddings {
  tensor_name: "RJB1:0"
  metadata_path: "meta/meta_RJB1.tsv"
}
embeddings {
  tensor_name: "RRE0:0"
  metadata_path: "meta/meta_RRE0.tsv"
}
embeddings {
  tensor_name: "DAC2:0"
  metadata_path: "meta/meta_DAC2.tsv"
}
embeddings {
  tensor_name: "JRH0:0"
  metadata_path: "meta/meta_JRH0.tsv"
}
embeddings {
  tensor_name: "FWK0:0"
  metadata_path: "meta/meta_FWK0.tsv"
}
embeddings {
  tensor_name: "TQC0:0"
  metadata_path: "meta/meta_TQC0.tsv"
}
embeddings {
  tensor_name: "CMR0:0"
  metadata_path: "meta/meta_CMR0.tsv"
}
embeddings {
  tensor_name: "JAI0:0"
  metadata_path: "meta/meta_JAI0.tsv"
}
embeddings {
  tensor_name: "EEH0:0"
  metadata_path: "meta/meta_EEH0.tsv"
}
embeddings {
  tensor_name: "CDR1:0"
  metadata_path: "meta/meta_CDR1.tsv"
}
embeddings {
  tensor_name: "SJW0:0"
  metadata_path: "meta/meta_SJW0.tsv"
}
embeddings {
  tensor_name: "EDR0:0"
  metadata_path: "meta/meta_EDR0.tsv"
}
embeddings {
  tensor_name: "DKS0:0"
  metadata_path: "meta/meta_DKS0.tsv"
}
embeddings {
  tensor_name: "TKD0:0"
  metadata_path: "meta/meta_TKD0.tsv"
}
embeddings {
  tensor_name: "HBS0:0"
  metadata_path: "meta/meta_HBS0.tsv"
}
embeddings {
  tensor_name: "GMD0:0"
  metadata_path: "meta/meta_GMD0.tsv"
}
embeddings {
  tensor_name: "ABC0:0"
  metadata_path: "meta/meta_ABC0.tsv"
}
embeddings {
  tensor_name: "ILB0:0"
  metadata_path: "meta/meta_ILB0.tsv"
}
embeddings {
  tensor_name: "MJB1:0"
  metadata_path: "meta/meta_MJB1.tsv"
}
embeddings {
  tensor_name: "HPG0:0"
  metadata_path: "meta/meta_HPG0.tsv"
}
embeddings {
  tensor_name: "BPM0:0"
  metadata_path: "meta/meta_BPM0.tsv"
}
embeddings {
  tensor_name: "SFV0:0"
  metadata_path: "meta/meta_SFV0.tsv"
}
embeddings {
  tensor_name: "TPG0:0"
  metadata_path: "meta/meta_TPG0.tsv"
}
embeddings {
  tensor_name: "GSH0:0"
  metadata_path: "meta/meta_GSH0.tsv"
}
embeddings {
  tensor_name: "SAG0:0"
  metadata_path: "meta/meta_SAG0.tsv"
}
embeddings {
  tensor_name: "KSR0:0"
  metadata_path: "meta/meta_KSR0.tsv"
}
embeddings {
  tensor_name: "NKL0:0"
  metadata_path: "meta/meta_NKL0.tsv"
}
embeddings {
  tensor_name: "GMB0:0"
  metadata_path: "meta/meta_GMB0.tsv"
}
embeddings {
  tensor_name: "KLC0:0"
  metadata_path: "meta/meta_KLC0.tsv"
}
embeddings {
  tensor_name: "CRZ0:0"
  metadata_path: "meta/meta_CRZ0.tsv"
}
embeddings {
  tensor_name: "DWA0:0"
  metadata_path: "meta/meta_DWA0.tsv"
}
embeddings {
  tensor_name: "CTM0:0"
  metadata_path: "meta/meta_CTM0.tsv"
}
embeddings {
  tensor_name: "WEW0:0"
  metadata_path: "meta/meta_WEW0.tsv"
}
embeddings {
  tensor_name: "RWS0:0"
  metadata_path: "meta/meta_RWS0.tsv"
}
embeddings {
  tensor_name: "PLB0:0"
  metadata_path: "meta/meta_PLB0.tsv"
}
embeddings {
  tensor_name: "ETB0:0"
  metadata_path: "meta/meta_ETB0.tsv"
}
embeddings {
  tensor_name: "JAS0:0"
  metadata_path: "meta/meta_JAS0.tsv"
}
embeddings {
  tensor_name: "FGK0:0"
  metadata_path: "meta/meta_FGK0.tsv"
}
embeddings {
  tensor_name: "PFU0:0"
  metadata_path: "meta/meta_PFU0.tsv"
}
embeddings {
  tensor_name: "STF0:0"
  metadata_path: "meta/meta_STF0.tsv"
}
embeddings {
  tensor_name: "GAW0:0"
  metadata_path: "meta/meta_GAW0.tsv"
}
embeddings {
  tensor_name: "MJF0:0"
  metadata_path: "meta/meta_MJF0.tsv"
}
embeddings {
  tensor_name: "MDM2:0"
  metadata_path: "meta/meta_MDM2.tsv"
}
embeddings {
  tensor_name: "JSP0:0"
  metadata_path: "meta/meta_JSP0.tsv"
}
embeddings {
  tensor_name: "CRC0:0"
  metadata_path: "meta/meta_CRC0.tsv"
}
embeddings {
  tensor_name: "TMN0:0"
  metadata_path: "meta/meta_TMN0.tsv"
}
embeddings {
  tensor_name: "PAZ0:0"
  metadata_path: "meta/meta_PAZ0.tsv"
}
embeddings {
  tensor_name: "RAV0:0"
  metadata_path: "meta/meta_RAV0.tsv"
}
embeddings {
  tensor_name: "RXB0:0"
  metadata_path: "meta/meta_RXB0.tsv"
}
embeddings {
  tensor_name: "PKT0:0"
  metadata_path: "meta/meta_PKT0.tsv"
}
embeddings {
  tensor_name: "JEM0:0"
  metadata_path: "meta/meta_JEM0.tsv"
}
embeddings {
  tensor_name: "JMA0:0"
  metadata_path: "meta/meta_JMA0.tsv"
}
embeddings {
  tensor_name: "CHH0:0"
  metadata_path: "meta/meta_CHH0.tsv"
}
embeddings {
  tensor_name: "DLB0:0"
  metadata_path: "meta/meta_DLB0.tsv"
}
embeddings {
  tensor_name: "PWM0:0"
  metadata_path: "meta/meta_PWM0.tsv"
}
embeddings {
  tensor_name: "TLC0:0"
  metadata_path: "meta/meta_TLC0.tsv"
}
embeddings {
  tensor_name: "JCS0:0"
  metadata_path: "meta/meta_JCS0.tsv"
}
embeddings {
  tensor_name: "PAB0:0"
  metadata_path: "meta/meta_PAB0.tsv"
}
embeddings {
  tensor_name: "JWB0:0"
  metadata_path: "meta/meta_JWB0.tsv"
}
embeddings {
  tensor_name: "MKF0:0"
  metadata_path: "meta/meta_MKF0.tsv"
}
embeddings {
  tensor_name: "JHI0:0"
  metadata_path: "meta/meta_JHI0.tsv"
}
embeddings {
  tensor_name: "JLG0:0"
  metadata_path: "meta/meta_JLG0.tsv"
}
embeddings {
  tensor_name: "DLD0:0"
  metadata_path: "meta/meta_DLD0.tsv"
}
embeddings {
  tensor_name: "HMG0:0"
  metadata_path: "meta/meta_HMG0.tsv"
}
embeddings {
  tensor_name: "RKO0:0"
  metadata_path: "meta/meta_RKO0.tsv"
}
embeddings {
  tensor_name: "CEM0:0"
  metadata_path: "meta/meta_CEM0.tsv"
}
embeddings {
  tensor_name: "MMH0:0"
  metadata_path: "meta/meta_MMH0.tsv"
}
embeddings {
  tensor_name: "DWM0:0"
  metadata_path: "meta/meta_DWM0.tsv"
}
embeddings {
  tensor_name: "SVS0:0"
  metadata_path: "meta/meta_SVS0.tsv"
}
embeddings {
  tensor_name: "BWM0:0"
  metadata_path: "meta/meta_BWM0.tsv"
}
embeddings {
  tensor_name: "VRW0:0"
  metadata_path: "meta/meta_VRW0.tsv"
}
embeddings {
  tensor_name: "CEG0:0"
  metadata_path: "meta/meta_CEG0.tsv"
}
embeddings {
  tensor_name: "DRB0:0"
  metadata_path: "meta/meta_DRB0.tsv"
}
embeddings {
  tensor_name: "SRR0:0"
  metadata_path: "meta/meta_SRR0.tsv"
}
embeddings {
  tensor_name: "JXP0:0"
  metadata_path: "meta/meta_JXP0.tsv"
}
embeddings {
  tensor_name: "PEB0:0"
  metadata_path: "meta/meta_PEB0.tsv"
}
embeddings {
  tensor_name: "RES0:0"
  metadata_path: "meta/meta_RES0.tsv"
}
embeddings {
  tensor_name: "JEE0:0"
  metadata_path: "meta/meta_JEE0.tsv"
}
embeddings {
  tensor_name: "KJO0:0"
  metadata_path: "meta/meta_KJO0.tsv"
}
embeddings {
  tensor_name: "JDE0:0"
  metadata_path: "meta/meta_JDE0.tsv"
}
embeddings {
  tensor_name: "TPR0:0"
  metadata_path: "meta/meta_TPR0.tsv"
}
embeddings {
  tensor_name: "BCH0:0"
  metadata_path: "meta/meta_BCH0.tsv"
}
embeddings {
  tensor_name: "RLJ0:0"
  metadata_path: "meta/meta_RLJ0.tsv"
}
embeddings {
  tensor_name: "LAS0:0"
  metadata_path: "meta/meta_LAS0.tsv"
}
embeddings {
  tensor_name: "DHL0:0"
  metadata_path: "meta/meta_DHL0.tsv"
}
embeddings {
  tensor_name: "CMJ0:0"
  metadata_path: "meta/meta_CMJ0.tsv"
}
embeddings {
  tensor_name: "DFB0:0"
  metadata_path: "meta/meta_DFB0.tsv"
}
embeddings {
  tensor_name: "RFK0:0"
  metadata_path: "meta/meta_RFK0.tsv"
}
embeddings {
  tensor_name: "GES0:0"
  metadata_path: "meta/meta_GES0.tsv"
}
embeddings {
  tensor_name: "GAR0:0"
  metadata_path: "meta/meta_GAR0.tsv"
}
embeddings {
  tensor_name: "MAA0:0"
  metadata_path: "meta/meta_MAA0.tsv"
}
embeddings {
  tensor_name: "CAJ0:0"
  metadata_path: "meta/meta_CAJ0.tsv"
}
embeddings {
  tensor_name: "RAB1:0"
  metadata_path: "meta/meta_RAB1.tsv"
}
embeddings {
  tensor_name: "DRD0:0"
  metadata_path: "meta/meta_DRD0.tsv"
}
embeddings {
  tensor_name: "HJB0:0"
  metadata_path: "meta/meta_HJB0.tsv"
}
embeddings {
  tensor_name: "CDR0:0"
  metadata_path: "meta/meta_CDR0.tsv"
}
embeddings {
  tensor_name: "JES0:0"
  metadata_path: "meta/meta_JES0.tsv"
}
embeddings {
  tensor_name: "MAG0:0"
  metadata_path: "meta/meta_MAG0.tsv"
}
embeddings {
  tensor_name: "JAE0:0"
  metadata_path: "meta/meta_JAE0.tsv"
}
embeddings {
  tensor_name: "RGG0:0"
  metadata_path: "meta/meta_RGG0.tsv"
}
embeddings {
  tensor_name: "MEB0:0"
  metadata_path: "meta/meta_MEB0.tsv"
}
embeddings {
  tensor_name: "SMM0:0"
  metadata_path: "meta/meta_SMM0.tsv"
}
embeddings {
  tensor_name: "REB0:0"
  metadata_path: "meta/meta_REB0.tsv"
}
embeddings {
  tensor_name: "ESJ0:0"
  metadata_path: "meta/meta_ESJ0.tsv"
}
embeddings {
  tensor_name: "MAH1:0"
  metadata_path: "meta/meta_MAH1.tsv"
}
embeddings {
  tensor_name: "DPS0:0"
  metadata_path: "meta/meta_DPS0.tsv"
}
embeddings {
  tensor_name: "KDR0:0"
  metadata_path: "meta/meta_KDR0.tsv"
}
embeddings {
  tensor_name: "DKN0:0"
  metadata_path: "meta/meta_DKN0.tsv"
}
embeddings {
  tensor_name: "CJF0:0"
  metadata_path: "meta/meta_CJF0.tsv"
}
embeddings {
  tensor_name: "JJM0:0"
  metadata_path: "meta/meta_JJM0.tsv"
}
embeddings {
  tensor_name: "VFB0:0"
  metadata_path: "meta/meta_VFB0.tsv"
}
embeddings {
  tensor_name: "SMS0:0"
  metadata_path: "meta/meta_SMS0.tsv"
}
embeddings {
  tensor_name: "CLM0:0"
  metadata_path: "meta/meta_CLM0.tsv"
}
embeddings {
  tensor_name: "JFC0:0"
  metadata_path: "meta/meta_JFC0.tsv"
}
embeddings {
  tensor_name: "JDM0:0"
  metadata_path: "meta/meta_JDM0.tsv"
}
embeddings {
  tensor_name: "EFG0:0"
  metadata_path: "meta/meta_EFG0.tsv"
}
embeddings {
  tensor_name: "TKP0:0"
  metadata_path: "meta/meta_TKP0.tsv"
}
embeddings {
  tensor_name: "MCM0:0"
  metadata_path: "meta/meta_MCM0.tsv"
}
embeddings {
  tensor_name: "ESG0:0"
  metadata_path: "meta/meta_ESG0.tsv"
}
embeddings {
  tensor_name: "TJM0:0"
  metadata_path: "meta/meta_TJM0.tsv"
}
embeddings {
  tensor_name: "DLS0:0"
  metadata_path: "meta/meta_DLS0.tsv"
}
embeddings {
  tensor_name: "SLB0:0"
  metadata_path: "meta/meta_SLB0.tsv"
}
embeddings {
  tensor_name: "DEM0:0"
  metadata_path: "meta/meta_DEM0.tsv"
}
embeddings {
  tensor_name: "MJU0:0"
  metadata_path: "meta/meta_MJU0.tsv"
}
embeddings {
  tensor_name: "LJG0:0"
  metadata_path: "meta/meta_LJG0.tsv"
}
embeddings {
  tensor_name: "DTD0:0"
  metadata_path: "meta/meta_DTD0.tsv"
}
embeddings {
  tensor_name: "TRC0:0"
  metadata_path: "meta/meta_TRC0.tsv"
}
embeddings {
  tensor_name: "CDC0:0"
  metadata_path: "meta/meta_CDC0.tsv"
}
embeddings {
  tensor_name: "SPM0:0"
  metadata_path: "meta/meta_SPM0.tsv"
}
embeddings {
  tensor_name: "JLM0:0"
  metadata_path: "meta/meta_JLM0.tsv"
}
embeddings {
  tensor_name: "DTB0:0"
  metadata_path: "meta/meta_DTB0.tsv"
}
embeddings {
  tensor_name: "RMS1:0"
  metadata_path: "meta/meta_RMS1.tsv"
}
embeddings {
  tensor_name: "CAE0:0"
  metadata_path: "meta/meta_CAE0.tsv"
}
embeddings {
  tensor_name: "DVC0:0"
  metadata_path: "meta/meta_DVC0.tsv"
}
embeddings {
  tensor_name: "KRG0:0"
  metadata_path: "meta/meta_KRG0.tsv"
}
embeddings {
  tensor_name: "DHC0:0"
  metadata_path: "meta/meta_DHC0.tsv"
}
embeddings {
  tensor_name: "RMS0:0"
  metadata_path: "meta/meta_RMS0.tsv"
}
embeddings {
  tensor_name: "MLM0:0"
  metadata_path: "meta/meta_MLM0.tsv"
}
embeddings {
  tensor_name: "ELC0:0"
  metadata_path: "meta/meta_ELC0.tsv"
}
embeddings {
  tensor_name: "RWS1:0"
  metadata_path: "meta/meta_RWS1.tsv"
}
embeddings {
  tensor_name: "CPM0:0"
  metadata_path: "meta/meta_CPM0.tsv"
}
embeddings {
  tensor_name: "JMG0:0"
  metadata_path: "meta/meta_JMG0.tsv"
}
embeddings {
  tensor_name: "AKS0:0"
  metadata_path: "meta/meta_AKS0.tsv"
}
embeddings {
  tensor_name: "MDB0:0"
  metadata_path: "meta/meta_MDB0.tsv"
}
embeddings {
  tensor_name: "KDB0:0"
  metadata_path: "meta/meta_KDB0.tsv"
}
embeddings {
  tensor_name: "JDM1:0"
  metadata_path: "meta/meta_JDM1.tsv"
}
embeddings {
  tensor_name: "BAR0:0"
  metadata_path: "meta/meta_BAR0.tsv"
}
embeddings {
  tensor_name: "SBK0:0"
  metadata_path: "meta/meta_SBK0.tsv"
}
embeddings {
  tensor_name: "JDH0:0"
  metadata_path: "meta/meta_JDH0.tsv"
}
embeddings {
  tensor_name: "KDW0:0"
  metadata_path: "meta/meta_KDW0.tsv"
}
embeddings {
  tensor_name: "LMK0:0"
  metadata_path: "meta/meta_LMK0.tsv"
}
embeddings {
  tensor_name: "JBG0:0"
  metadata_path: "meta/meta_JBG0.tsv"
}
embeddings {
  tensor_name: "KDE0:0"
  metadata_path: "meta/meta_KDE0.tsv"
}
embeddings {
  tensor_name: "SFH0:0"
  metadata_path: "meta/meta_SFH0.tsv"
}
embeddings {
  tensor_name: "EJS0:0"
  metadata_path: "meta/meta_EJS0.tsv"
}
embeddings {
  tensor_name: "TML0:0"
  metadata_path: "meta/meta_TML0.tsv"
}
embeddings {
  tensor_name: "WBT0:0"
  metadata_path: "meta/meta_WBT0.tsv"
}
embeddings {
  tensor_name: "DWH0:0"
  metadata_path: "meta/meta_DWH0.tsv"
}
embeddings {
  tensor_name: "SAS0:0"
  metadata_path: "meta/meta_SAS0.tsv"
}
embeddings {
  tensor_name: "KLT0:0"
  metadata_path: "meta/meta_KLT0.tsv"
}
embeddings {
  tensor_name: "JAR0:0"
  metadata_path: "meta/meta_JAR0.tsv"
}
embeddings {
  tensor_name: "PJF0:0"
  metadata_path: "meta/meta_PJF0.tsv"
}
embeddings {
  tensor_name: "TAA0:0"
  metadata_path: "meta/meta_TAA0.tsv"
}
embeddings {
  tensor_name: "JRH1:0"
  metadata_path: "meta/meta_JRH1.tsv"
}
embeddings {
  tensor_name: "DJM0:0"
  metadata_path: "meta/meta_DJM0.tsv"
}
embeddings {
  tensor_name: "TXS0:0"
  metadata_path: "meta/meta_TXS0.tsv"
}
embeddings {
  tensor_name: "HIT0:0"
  metadata_path: "meta/meta_HIT0.tsv"
}
embeddings {
  tensor_name: "TJS0:0"
  metadata_path: "meta/meta_TJS0.tsv"
}
embeddings {
  tensor_name: "CHL0:0"
  metadata_path: "meta/meta_CHL0.tsv"
}
embeddings {
  tensor_name: "GWR0:0"
  metadata_path: "meta/meta_GWR0.tsv"
}
embeddings {
  tensor_name: "JRA0:0"
  metadata_path: "meta/meta_JRA0.tsv"
}
embeddings {
  tensor_name: "KCL0:0"
  metadata_path: "meta/meta_KCL0.tsv"
}
embeddings {
  tensor_name: "JMD0:0"
  metadata_path: "meta/meta_JMD0.tsv"
}
embeddings {
  tensor_name: "BDG0:0"
  metadata_path: "meta/meta_BDG0.tsv"
}
embeddings {
  tensor_name: "TAB0:0"
  metadata_path: "meta/meta_TAB0.tsv"
}
embeddings {
  tensor_name: "RLL0:0"
  metadata_path: "meta/meta_RLL0.tsv"
}
embeddings {
  tensor_name: "SEM0:0"
  metadata_path: "meta/meta_SEM0.tsv"
}
embeddings {
  tensor_name: "RDS0:0"
  metadata_path: "meta/meta_RDS0.tsv"
}
embeddings {
  tensor_name: "DAS0:0"
  metadata_path: "meta/meta_DAS0.tsv"
}
embeddings {
  tensor_name: "SAT1:0"
  metadata_path: "meta/meta_SAT1.tsv"
}
embeddings {
  tensor_name: "MWB0:0"
  metadata_path: "meta/meta_MWB0.tsv"
}
embeddings {
  tensor_name: "KLR0:0"
  metadata_path: "meta/meta_KLR0.tsv"
}
embeddings {
  tensor_name: "GCS0:0"
  metadata_path: "meta/meta_GCS0.tsv"
}
embeddings {
  tensor_name: "MJB0:0"
  metadata_path: "meta/meta_MJB0.tsv"
}
embeddings {
  tensor_name: "JWT0:0"
  metadata_path: "meta/meta_JWT0.tsv"
}
embeddings {
  tensor_name: "DLH0:0"
  metadata_path: "meta/meta_DLH0.tsv"
}
embeddings {
  tensor_name: "RTC0:0"
  metadata_path: "meta/meta_RTC0.tsv"
}
embeddings {
  tensor_name: "DSS1:0"
  metadata_path: "meta/meta_DSS1.tsv"
}
embeddings {
  tensor_name: "JMM0:0"
  metadata_path: "meta/meta_JMM0.tsv"
}
embeddings {
  tensor_name: "PGL0:0"
  metadata_path: "meta/meta_PGL0.tsv"
}
embeddings {
  tensor_name: "MAB1:0"
  metadata_path: "meta/meta_MAB1.tsv"
}
embeddings {
  tensor_name: "SDS0:0"
  metadata_path: "meta/meta_SDS0.tsv"
}
embeddings {
  tensor_name: "PMY0:0"
  metadata_path: "meta/meta_PMY0.tsv"
}
embeddings {
  tensor_name: "BJV0:0"
  metadata_path: "meta/meta_BJV0.tsv"
}
embeddings {
  tensor_name: "MDS0:0"
  metadata_path: "meta/meta_MDS0.tsv"
}
embeddings {
  tensor_name: "MPG0:0"
  metadata_path: "meta/meta_MPG0.tsv"
}
embeddings {
  tensor_name: "WSB0:0"
  metadata_path: "meta/meta_WSB0.tsv"
}
embeddings {
  tensor_name: "RMG0:0"
  metadata_path: "meta/meta_RMG0.tsv"
}
embeddings {
  tensor_name: "RFL0:0"
  metadata_path: "meta/meta_RFL0.tsv"
}
embeddings {
  tensor_name: "PAR0:0"
  metadata_path: "meta/meta_PAR0.tsv"
}
embeddings {
  tensor_name: "EAL0:0"
  metadata_path: "meta/meta_EAL0.tsv"
}
embeddings {
  tensor_name: "SRH0:0"
  metadata_path: "meta/meta_SRH0.tsv"
}
embeddings {
  tensor_name: "ISB0:0"
  metadata_path: "meta/meta_ISB0.tsv"
}
embeddings {
  tensor_name: "RTJ0:0"
  metadata_path: "meta/meta_RTJ0.tsv"
}
embeddings {
  tensor_name: "AJW0:0"
  metadata_path: "meta/meta_AJW0.tsv"
}
embeddings {
  tensor_name: "SJS1:0"
  metadata_path: "meta/meta_SJS1.tsv"
}
embeddings {
  tensor_name: "RCZ0:0"
  metadata_path: "meta/meta_RCZ0.tsv"
}
embeddings {
  tensor_name: "TLS0:0"
  metadata_path: "meta/meta_TLS0.tsv"
}
embeddings {
  tensor_name: "LEL0:0"
  metadata_path: "meta/meta_LEL0.tsv"
}
embeddings {
  tensor_name: "CLK0:0"
  metadata_path: "meta/meta_CLK0.tsv"
}
embeddings {
  tensor_name: "JJG0:0"
  metadata_path: "meta/meta_JJG0.tsv"
}
embeddings {
  tensor_name: "LAC0:0"
  metadata_path: "meta/meta_LAC0.tsv"
}
embeddings {
  tensor_name: "GRP0:0"
  metadata_path: "meta/meta_GRP0.tsv"
}
embeddings {
  tensor_name: "REM0:0"
  metadata_path: "meta/meta_REM0.tsv"
}
embeddings {
  tensor_name: "JEB1:0"
  metadata_path: "meta/meta_JEB1.tsv"
}
embeddings {
  tensor_name: "NET0:0"
  metadata_path: "meta/meta_NET0.tsv"
}
embeddings {
  tensor_name: "LSH0:0"
  metadata_path: "meta/meta_LSH0.tsv"
}
embeddings {
  tensor_name: "RDD0:0"
  metadata_path: "meta/meta_RDD0.tsv"
}
embeddings {
  tensor_name: "VJH0:0"
  metadata_path: "meta/meta_VJH0.tsv"
}
embeddings {
  tensor_name: "DJH0:0"
  metadata_path: "meta/meta_DJH0.tsv"
}
embeddings {
  tensor_name: "MWS0:0"
  metadata_path: "meta/meta_MWS0.tsv"
}
embeddings {
  tensor_name: "JTC0:0"
  metadata_path: "meta/meta_JTC0.tsv"
}
embeddings {
  tensor_name: "HRM0:0"
  metadata_path: "meta/meta_HRM0.tsv"
}
embeddings {
  tensor_name: "PSW0:0"
  metadata_path: "meta/meta_PSW0.tsv"
}
embeddings {
  tensor_name: "LJH0:0"
  metadata_path: "meta/meta_LJH0.tsv"
}
embeddings {
  tensor_name: "LTM0:0"
  metadata_path: "meta/meta_LTM0.tsv"
}
embeddings {
  tensor_name: "AEB0:0"
  metadata_path: "meta/meta_AEB0.tsv"
}
embeddings {
  tensor_name: "RBC0:0"
  metadata_path: "meta/meta_RBC0.tsv"
}
embeddings {
  tensor_name: "CMB0:0"
  metadata_path: "meta/meta_CMB0.tsv"
}
embeddings {
  tensor_name: "AFM0:0"
  metadata_path: "meta/meta_AFM0.tsv"
}
embeddings {
  tensor_name: "KLW0:0"
  metadata_path: "meta/meta_KLW0.tsv"
}
embeddings {
  tensor_name: "SLS0:0"
  metadata_path: "meta/meta_SLS0.tsv"
}
embeddings {
  tensor_name: "LBC0:0"
  metadata_path: "meta/meta_LBC0.tsv"
}
embeddings {
  tensor_name: "REH1:0"
  metadata_path: "meta/meta_REH1.tsv"
}
embeddings {
  tensor_name: "LKM0:0"
  metadata_path: "meta/meta_LKM0.tsv"
}
embeddings {
  tensor_name: "TDB0:0"
  metadata_path: "meta/meta_TDB0.tsv"
}
embeddings {
  tensor_name: "JJB0:0"
  metadata_path: "meta/meta_JJB0.tsv"
}
embeddings {
  tensor_name: "MEM0:0"
  metadata_path: "meta/meta_MEM0.tsv"
}
embeddings {
  tensor_name: "ALK0:0"
  metadata_path: "meta/meta_ALK0.tsv"
}
embeddings {
  tensor_name: "BJK0:0"
  metadata_path: "meta/meta_BJK0.tsv"
}
embeddings {
  tensor_name: "MDM1:0"
  metadata_path: "meta/meta_MDM1.tsv"
}
embeddings {
  tensor_name: "HXL0:0"
  metadata_path: "meta/meta_HXL0.tsv"
}
embeddings {
  tensor_name: "MAR0:0"
  metadata_path: "meta/meta_MAR0.tsv"
}
embeddings {
  tensor_name: "STK0:0"
  metadata_path: "meta/meta_STK0.tsv"
}
embeddings {
  tensor_name: "TBW0:0"
  metadata_path: "meta/meta_TBW0.tsv"
}
embeddings {
  tensor_name: "RMH0:0"
  metadata_path: "meta/meta_RMH0.tsv"
}
embeddings {
  tensor_name: "GRL0:0"
  metadata_path: "meta/meta_GRL0.tsv"
}
embeddings {
  tensor_name: "PRB0:0"
  metadata_path: "meta/meta_PRB0.tsv"
}
embeddings {
  tensor_name: "RGS0:0"
  metadata_path: "meta/meta_RGS0.tsv"
}
embeddings {
  tensor_name: "AHH0:0"
  metadata_path: "meta/meta_AHH0.tsv"
}
embeddings {
  tensor_name: "MDG0:0"
  metadata_path: "meta/meta_MDG0.tsv"
}
embeddings {
  tensor_name: "JSR0:0"
  metadata_path: "meta/meta_JSR0.tsv"
}
embeddings {
  tensor_name: "JPG0:0"
  metadata_path: "meta/meta_JPG0.tsv"
}
embeddings {
  tensor_name: "JVW0:0"
  metadata_path: "meta/meta_JVW0.tsv"
}
embeddings {
  tensor_name: "KMS0:0"
  metadata_path: "meta/meta_KMS0.tsv"
}
embeddings {
  tensor_name: "PMB0:0"
  metadata_path: "meta/meta_PMB0.tsv"
}
embeddings {
  tensor_name: "BBR0:0"
  metadata_path: "meta/meta_BBR0.tsv"
}
embeddings {
  tensor_name: "DRW0:0"
  metadata_path: "meta/meta_DRW0.tsv"
}
embeddings {
  tensor_name: "RCW0:0"
  metadata_path: "meta/meta_RCW0.tsv"
}
embeddings {
  tensor_name: "JWB1:0"
  metadata_path: "meta/meta_JWB1.tsv"
}
embeddings {
  tensor_name: "DEF0:0"
  metadata_path: "meta/meta_DEF0.tsv"
}
embeddings {
  tensor_name: "LNT0:0"
  metadata_path: "meta/meta_LNT0.tsv"
}
embeddings {
  tensor_name: "CEF0:0"
  metadata_path: "meta/meta_CEF0.tsv"
}
embeddings {
  tensor_name: "RJM3:0"
  metadata_path: "meta/meta_RJM3.tsv"
}
embeddings {
  tensor_name: "SJK0:0"
  metadata_path: "meta/meta_SJK0.tsv"
}
embeddings {
  tensor_name: "GMM0:0"
  metadata_path: "meta/meta_GMM0.tsv"
}
embeddings {
  tensor_name: "BGT0:0"
  metadata_path: "meta/meta_BGT0.tsv"
}
embeddings {
  tensor_name: "JPM1:0"
  metadata_path: "meta/meta_JPM1.tsv"
}
embeddings {
  tensor_name: "CAL0:0"
  metadata_path: "meta/meta_CAL0.tsv"
}
embeddings {
  tensor_name: "SJS0:0"
  metadata_path: "meta/meta_SJS0.tsv"
}
embeddings {
  tensor_name: "PPC0:0"
  metadata_path: "meta/meta_PPC0.tsv"
}
embeddings {
  tensor_name: "RAM0:0"
  metadata_path: "meta/meta_RAM0.tsv"
}
embeddings {
  tensor_name: "GJC0:0"
  metadata_path: "meta/meta_GJC0.tsv"
}
embeddings {
  tensor_name: "LLL0:0"
  metadata_path: "meta/meta_LLL0.tsv"
}
embeddings {
  tensor_name: "FMC0:0"
  metadata_path: "meta/meta_FMC0.tsv"
}
embeddings {
  tensor_name: "SLB1:0"
  metadata_path: "meta/meta_SLB1.tsv"
}
embeddings {
  tensor_name: "PCS0:0"
  metadata_path: "meta/meta_PCS0.tsv"
}
embeddings {
  tensor_name: "DAC0:0"
  metadata_path: "meta/meta_DAC0.tsv"
}
embeddings {
  tensor_name: "SSB0:0"
  metadata_path: "meta/meta_SSB0.tsv"
}
embeddings {
  tensor_name: "JDM2:0"
  metadata_path: "meta/meta_JDM2.tsv"
}
embeddings {
  tensor_name: "JLS0:0"
  metadata_path: "meta/meta_JLS0.tsv"
}
embeddings {
  tensor_name: "MDH0:0"
  metadata_path: "meta/meta_MDH0.tsv"
}
embeddings {
  tensor_name: "TLH0:0"
  metadata_path: "meta/meta_TLH0.tsv"
}
embeddings {
  tensor_name: "RJT0:0"
  metadata_path: "meta/meta_RJT0.tsv"
}
embeddings {
  tensor_name: "CMM0:0"
  metadata_path: "meta/meta_CMM0.tsv"
}
embeddings {
  tensor_name: "JSW0:0"
  metadata_path: "meta/meta_JSW0.tsv"
}
embeddings {
  tensor_name: "EGJ0:0"
  metadata_path: "meta/meta_EGJ0.tsv"
}
embeddings {
  tensor_name: "PRK0:0"
  metadata_path: "meta/meta_PRK0.tsv"
}
embeddings {
  tensor_name: "TDP0:0"
  metadata_path: "meta/meta_TDP0.tsv"
}
embeddings {
  tensor_name: "GLB0:0"
  metadata_path: "meta/meta_GLB0.tsv"
}
embeddings {
  tensor_name: "MAM0:0"
  metadata_path: "meta/meta_MAM0.tsv"
}
embeddings {
  tensor_name: "RJO0:0"
  metadata_path: "meta/meta_RJO0.tsv"
}
embeddings {
  tensor_name: "GAF0:0"
  metadata_path: "meta/meta_GAF0.tsv"
}
embeddings {
  tensor_name: "TLG0:0"
  metadata_path: "meta/meta_TLG0.tsv"
}
embeddings {
  tensor_name: "DLF0:0"
  metadata_path: "meta/meta_DLF0.tsv"
}
embeddings {
  tensor_name: "JDC0:0"
  metadata_path: "meta/meta_JDC0.tsv"
}
embeddings {
  tensor_name: "WDK0:0"
  metadata_path: "meta/meta_WDK0.tsv"
}
embeddings {
  tensor_name: "BMJ0:0"
  metadata_path: "meta/meta_BMJ0.tsv"
}
embeddings {
  tensor_name: "JRE0:0"
  metadata_path: "meta/meta_JRE0.tsv"
}
embeddings {
  tensor_name: "PGR0:0"
  metadata_path: "meta/meta_PGR0.tsv"
}
embeddings {
  tensor_name: "JMP0:0"
  metadata_path: "meta/meta_JMP0.tsv"
}
embeddings {
  tensor_name: "KJL0:0"
  metadata_path: "meta/meta_KJL0.tsv"
}
embeddings {
  tensor_name: "DML0:0"
  metadata_path: "meta/meta_DML0.tsv"
}
embeddings {
  tensor_name: "TLB0:0"
  metadata_path: "meta/meta_TLB0.tsv"
}
embeddings {
  tensor_name: "LJA0:0"
  metadata_path: "meta/meta_LJA0.tsv"
}
embeddings {
  tensor_name: "PRD0:0"
  metadata_path: "meta/meta_PRD0.tsv"
}
embeddings {
  tensor_name: "MWH0:0"
  metadata_path: "meta/meta_MWH0.tsv"
}
embeddings {
  tensor_name: "LNH0:0"
  metadata_path: "meta/meta_LNH0.tsv"
}
embeddings {
  tensor_name: "TCS0:0"
  metadata_path: "meta/meta_TCS0.tsv"
}
embeddings {
  tensor_name: "ABW0:0"
  metadata_path: "meta/meta_ABW0.tsv"
}
embeddings {
  tensor_name: "LAG0:0"
  metadata_path: "meta/meta_LAG0.tsv"
}
embeddings {
  tensor_name: "CXM0:0"
  metadata_path: "meta/meta_CXM0.tsv"
}
embeddings {
  tensor_name: "JFH0:0"
  metadata_path: "meta/meta_JFH0.tsv"
}
embeddings {
  tensor_name: "RML0:0"
  metadata_path: "meta/meta_RML0.tsv"
}
embeddings {
  tensor_name: "PAD0:0"
  metadata_path: "meta/meta_PAD0.tsv"
}
embeddings {
  tensor_name: "EAR0:0"
  metadata_path: "meta/meta_EAR0.tsv"
}
embeddings {
  tensor_name: "NLP0:0"
  metadata_path: "meta/meta_NLP0.tsv"
}
embeddings {
  tensor_name: "JRP0:0"
  metadata_path: "meta/meta_JRP0.tsv"
}
embeddings {
  tensor_name: "RAI0:0"
  metadata_path: "meta/meta_RAI0.tsv"
}
embeddings {
  tensor_name: "DWD0:0"
  metadata_path: "meta/meta_DWD0.tsv"
}
embeddings {
  tensor_name: "JRP1:0"
  metadata_path: "meta/meta_JRP1.tsv"
}
embeddings {
  tensor_name: "TEB0:0"
  metadata_path: "meta/meta_TEB0.tsv"
}
embeddings {
  tensor_name: "LMA0:0"
  metadata_path: "meta/meta_LMA0.tsv"
}
embeddings {
  tensor_name: "ADD0:0"
  metadata_path: "meta/meta_ADD0.tsv"
}
embeddings {
  tensor_name: "TAT1:0"
  metadata_path: "meta/meta_TAT1.tsv"
}
embeddings {
  tensor_name: "CMG0:0"
  metadata_path: "meta/meta_CMG0.tsv"
}
embeddings {
  tensor_name: "SEM1:0"
  metadata_path: "meta/meta_SEM1.tsv"
}
embeddings {
  tensor_name: "REW1:0"
  metadata_path: "meta/meta_REW1.tsv"
}
embeddings {
  tensor_name: "BCG0:0"
  metadata_path: "meta/meta_BCG0.tsv"
}
embeddings {
  tensor_name: "ADC0:0"
  metadata_path: "meta/meta_ADC0.tsv"
}
embeddings {
  tensor_name: "SDJ0:0"
  metadata_path: "meta/meta_SDJ0.tsv"
}
embeddings {
  tensor_name: "RHL0:0"
  metadata_path: "meta/meta_RHL0.tsv"
}
embeddings {
  tensor_name: "CTT0:0"
  metadata_path: "meta/meta_CTT0.tsv"
}
embeddings {
  tensor_name: "CSH0:0"
  metadata_path: "meta/meta_CSH0.tsv"
}
embeddings {
  tensor_name: "AKR0:0"
  metadata_path: "meta/meta_AKR0.tsv"
}
embeddings {
  tensor_name: "SDC0:0"
  metadata_path: "meta/meta_SDC0.tsv"
}
embeddings {
  tensor_name: "TAJ0:0"
  metadata_path: "meta/meta_TAJ0.tsv"
}
embeddings {
  tensor_name: "HES0:0"
  metadata_path: "meta/meta_HES0.tsv"
}
embeddings {
  tensor_name: "EAC0:0"
  metadata_path: "meta/meta_EAC0.tsv"
}
embeddings {
  tensor_name: "NMR0:0"
  metadata_path: "meta/meta_NMR0.tsv"
}
embeddings {
  tensor_name: "ADG0:0"
  metadata_path: "meta/meta_ADG0.tsv"
}
embeddings {
  tensor_name: "JAC0:0"
  metadata_path: "meta/meta_JAC0.tsv"
}
embeddings {
  tensor_name: "JEB0:0"
  metadata_path: "meta/meta_JEB0.tsv"
}
embeddings {
  tensor_name: "GWT0:0"
  metadata_path: "meta/meta_GWT0.tsv"
}
embeddings {
  tensor_name: "PAS0:0"
  metadata_path: "meta/meta_PAS0.tsv"
}
embeddings {
  tensor_name: "KDD0:0"
  metadata_path: "meta/meta_KDD0.tsv"
}
embeddings {
  tensor_name: "GXP0:0"
  metadata_path: "meta/meta_GXP0.tsv"
}
embeddings {
  tensor_name: "TRR0:0"
  metadata_path: "meta/meta_TRR0.tsv"
}
embeddings {
  tensor_name: "KAJ0:0"
  metadata_path: "meta/meta_KAJ0.tsv"
}
embeddings {
  tensor_name: "TDT0:0"
  metadata_path: "meta/meta_TDT0.tsv"
}
embeddings {
  tensor_name: "SES0:0"
  metadata_path: "meta/meta_SES0.tsv"
}
embeddings {
  tensor_name: "RPC0:0"
  metadata_path: "meta/meta_RPC0.tsv"
}
embeddings {
  tensor_name: "KLC1:0"
  metadata_path: "meta/meta_KLC1.tsv"
}
embeddings {
  tensor_name: "ALR0:0"
  metadata_path: "meta/meta_ALR0.tsv"
}
embeddings {
  tensor_name: "DDC0:0"
  metadata_path: "meta/meta_DDC0.tsv"
}
embeddings {
  tensor_name: "KLN0:0"
  metadata_path: "meta/meta_KLN0.tsv"
}
embeddings {
  tensor_name: "RNG0:0"
  metadata_path: "meta/meta_RNG0.tsv"
}
embeddings {
  tensor_name: "PAC0:0"
  metadata_path: "meta/meta_PAC0.tsv"
}
embeddings {
  tensor_name: "LKD0:0"
  metadata_path: "meta/meta_LKD0.tsv"
}
embeddings {
  tensor_name: "BMH0:0"
  metadata_path: "meta/meta_BMH0.tsv"
}
embeddings {
  tensor_name: "TMT0:0"
  metadata_path: "meta/meta_TMT0.tsv"
}
embeddings {
  tensor_name: "SCN0:0"
  metadata_path: "meta/meta_SCN0.tsv"
}
embeddings {
  tensor_name: "SDH0:0"
  metadata_path: "meta/meta_SDH0.tsv"
}
embeddings {
  tensor_name: "LNS0:0"
  metadata_path: "meta/meta_LNS0.tsv"
}
embeddings {
  tensor_name: "LET0:0"
  metadata_path: "meta/meta_LET0.tsv"
}
embeddings {
  tensor_name: "SKC0:0"
  metadata_path: "meta/meta_SKC0.tsv"
}
embeddings {
  tensor_name: "TRT0:0"
  metadata_path: "meta/meta_TRT0.tsv"
}
embeddings {
  tensor_name: "APB0:0"
  metadata_path: "meta/meta_APB0.tsv"
}
embeddings {
  tensor_name: "JXL0:0"
  metadata_path: "meta/meta_JXL0.tsv"
}
embeddings {
  tensor_name: "BSB0:0"
  metadata_path: "meta/meta_BSB0.tsv"
}
embeddings {
  tensor_name: "TJU0:0"
  metadata_path: "meta/meta_TJU0.tsv"
}
embeddings {
  tensor_name: "DMA0:0"
  metadata_path: "meta/meta_DMA0.tsv"
}
embeddings {
  tensor_name: "ARC0:0"
  metadata_path: "meta/meta_ARC0.tsv"
}
embeddings {
  tensor_name: "JWS0:0"
  metadata_path: "meta/meta_JWS0.tsv"
}
embeddings {
  tensor_name: "DSS0:0"
  metadata_path: "meta/meta_DSS0.tsv"
}
embeddings {
  tensor_name: "HXS0:0"
  metadata_path: "meta/meta_HXS0.tsv"
}
embeddings {
  tensor_name: "JWG0:0"
  metadata_path: "meta/meta_JWG0.tsv"
}
embeddings {
  tensor_name: "RLD0:0"
  metadata_path: "meta/meta_RLD0.tsv"
}
embeddings {
  tensor_name: "HMR0:0"
  metadata_path: "meta/meta_HMR0.tsv"
}
embeddings {
  tensor_name: "BAS0:0"
  metadata_path: "meta/meta_BAS0.tsv"
}
embeddings {
  tensor_name: "MGK0:0"
  metadata_path: "meta/meta_MGK0.tsv"
}
embeddings {
  tensor_name: "BOM0:0"
  metadata_path: "meta/meta_BOM0.tsv"
}
embeddings {
  tensor_name: "SRG0:0"
  metadata_path: "meta/meta_SRG0.tsv"
}
embeddings {
  tensor_name: "RJS0:0"
  metadata_path: "meta/meta_RJS0.tsv"
}
embeddings {
  tensor_name: "EXM0:0"
  metadata_path: "meta/meta_EXM0.tsv"
}
embeddings {
  tensor_name: "MXS0:0"
  metadata_path: "meta/meta_MXS0.tsv"
}
embeddings {
  tensor_name: "VLO0:0"
  metadata_path: "meta/meta_VLO0.tsv"
}
embeddings {
  tensor_name: "FXS0:0"
  metadata_path: "meta/meta_FXS0.tsv"
}
embeddings {
  tensor_name: "WVW0:0"
  metadata_path: "meta/meta_WVW0.tsv"
}
embeddings {
  tensor_name: "DLC2:0"
  metadata_path: "meta/meta_DLC2.tsv"
}
embeddings {
  tensor_name: "ARW0:0"
  metadata_path: "meta/meta_ARW0.tsv"
}
embeddings {
  tensor_name: "HLM0:0"
  metadata_path: "meta/meta_HLM0.tsv"
}
embeddings {
  tensor_name: "EDW0:0"
  metadata_path: "meta/meta_EDW0.tsv"
}
embeddings {
  tensor_name: "DSC0:0"
  metadata_path: "meta/meta_DSC0.tsv"
}
embeddings {
  tensor_name: "GAG0:0"
  metadata_path: "meta/meta_GAG0.tsv"
}
embeddings {
  tensor_name: "KDT0:0"
  metadata_path: "meta/meta_KDT0.tsv"
}
embeddings {
  tensor_name: "PAM0:0"
  metadata_path: "meta/meta_PAM0.tsv"
}
embeddings {
  tensor_name: "TBR0:0"
  metadata_path: "meta/meta_TBR0.tsv"
}
embeddings {
  tensor_name: "TMG0:0"
  metadata_path: "meta/meta_TMG0.tsv"
}
embeddings {
  tensor_name: "WCH0:0"
  metadata_path: "meta/meta_WCH0.tsv"
}
embeddings {
  tensor_name: "PAM1:0"
  metadata_path: "meta/meta_PAM1.tsv"
}
embeddings {
  tensor_name: "ESD0:0"
  metadata_path: "meta/meta_ESD0.tsv"
}
embeddings {
  tensor_name: "WAC0:0"
  metadata_path: "meta/meta_WAC0.tsv"
}
embeddings {
  tensor_name: "TAT0:0"
  metadata_path: "meta/meta_TAT0.tsv"
}
embeddings {
  tensor_name: "VMH0:0"
  metadata_path: "meta/meta_VMH0.tsv"
}
embeddings {
  tensor_name: "MVP0:0"
  metadata_path: "meta/meta_MVP0.tsv"
}
embeddings {
  tensor_name: "JPM0:0"
  metadata_path: "meta/meta_JPM0.tsv"
}
embeddings {
  tensor_name: "JFR0:0"
  metadata_path: "meta/meta_JFR0.tsv"
}
embeddings {
  tensor_name: "KES0:0"
  metadata_path: "meta/meta_KES0.tsv"
}
embeddings {
  tensor_name: "RPC1:0"
  metadata_path: "meta/meta_RPC1.tsv"
}
embeddings {
  tensor_name: "MLD0:0"
  metadata_path: "meta/meta_MLD0.tsv"
}
embeddings {
  tensor_name: "WRP0:0"
  metadata_path: "meta/meta_WRP0.tsv"
}
embeddings {
  tensor_name: "EME0:0"
  metadata_path: "meta/meta_EME0.tsv"
}
embeddings {
  tensor_name: "DMS0:0"
  metadata_path: "meta/meta_DMS0.tsv"
}
embeddings {
  tensor_name: "KCH0:0"
  metadata_path: "meta/meta_KCH0.tsv"
}
embeddings {
  tensor_name: "FRM0:0"
  metadata_path: "meta/meta_FRM0.tsv"
}
embeddings {
  tensor_name: "SMR0:0"
  metadata_path: "meta/meta_SMR0.tsv"
}
embeddings {
  tensor_name: "MKC0:0"
  metadata_path: "meta/meta_MKC0.tsv"
}
embeddings {
  tensor_name: "MGG0:0"
  metadata_path: "meta/meta_MGG0.tsv"
}
embeddings {
  tensor_name: "JLG1:0"
  metadata_path: "meta/meta_JLG1.tsv"
}
embeddings {
  tensor_name: "CAG0:0"
  metadata_path: "meta/meta_CAG0.tsv"
}
embeddings {
  tensor_name: "RJM1:0"
  metadata_path: "meta/meta_RJM1.tsv"
}
embeddings {
  tensor_name: "RKM0:0"
  metadata_path: "meta/meta_RKM0.tsv"
}
embeddings {
  tensor_name: "REH0:0"
  metadata_path: "meta/meta_REH0.tsv"
}
embeddings {
  tensor_name: "CAL1:0"
  metadata_path: "meta/meta_CAL1.tsv"
}
embeddings {
  tensor_name: "RLK0:0"
  metadata_path: "meta/meta_RLK0.tsv"
}
embeddings {
  tensor_name: "JJJ0:0"
  metadata_path: "meta/meta_JJJ0.tsv"
}
embeddings {
  tensor_name: "ROA0:0"
  metadata_path: "meta/meta_ROA0.tsv"
}
embeddings {
  tensor_name: "PLS0:0"
  metadata_path: "meta/meta_PLS0.tsv"
}
embeddings {
  tensor_name: "CMH0:0"
  metadata_path: "meta/meta_CMH0.tsv"
}
embeddings {
  tensor_name: "HEW0:0"
  metadata_path: "meta/meta_HEW0.tsv"
}
embeddings {
  tensor_name: "TER0:0"
  metadata_path: "meta/meta_TER0.tsv"
}
embeddings {
  tensor_name: "KXL0:0"
  metadata_path: "meta/meta_KXL0.tsv"
}
embeddings {
  tensor_name: "PRT0:0"
  metadata_path: "meta/meta_PRT0.tsv"
}
embeddings {
  tensor_name: "DAC1:0"
  metadata_path: "meta/meta_DAC1.tsv"
}
embeddings {
  tensor_name: "MBS0:0"
  metadata_path: "meta/meta_MBS0.tsv"
}
embeddings {
  tensor_name: "MBG0:0"
  metadata_path: "meta/meta_MBG0.tsv"
}
embeddings {
  tensor_name: "JBR0:0"
  metadata_path: "meta/meta_JBR0.tsv"
}
embeddings {
  tensor_name: "RRK0:0"
  metadata_path: "meta/meta_RRK0.tsv"
}
embeddings {
  tensor_name: "SJG0:0"
  metadata_path: "meta/meta_SJG0.tsv"
}
embeddings {
  tensor_name: "BLV0:0"
  metadata_path: "meta/meta_BLV0.tsv"
}
embeddings {
  tensor_name: "DBB0:0"
  metadata_path: "meta/meta_DBB0.tsv"
}
embeddings {
  tensor_name: "WGR0:0"
  metadata_path: "meta/meta_WGR0.tsv"
}
embeddings {
  tensor_name: "GJF0:0"
  metadata_path: "meta/meta_GJF0.tsv"
}
embeddings {
  tensor_name: "DCM0:0"
  metadata_path: "meta/meta_DCM0.tsv"
}
embeddings {
  tensor_name: "DAW0:0"
  metadata_path: "meta/meta_DAW0.tsv"
}
embeddings {
  tensor_name: "RVG0:0"
  metadata_path: "meta/meta_RVG0.tsv"
}
embeddings {
  tensor_name: "JKL0:0"
  metadata_path: "meta/meta_JKL0.tsv"
}
embeddings {
  tensor_name: "CYL0:0"
  metadata_path: "meta/meta_CYL0.tsv"
}
embeddings {
  tensor_name: "SKP0:0"
  metadata_path: "meta/meta_SKP0.tsv"
}
embeddings {
  tensor_name: "MGD0:0"
  metadata_path: "meta/meta_MGD0.tsv"
}
embeddings {
  tensor_name: "GJD0:0"
  metadata_path: "meta/meta_GJD0.tsv"
}
embeddings {
  tensor_name: "SAT0:0"
  metadata_path: "meta/meta_SAT0.tsv"
}
embeddings {
  tensor_name: "LJC0:0"
  metadata_path: "meta/meta_LJC0.tsv"
}
embeddings {
  tensor_name: "JLB0:0"
  metadata_path: "meta/meta_JLB0.tsv"
}
embeddings {
  tensor_name: "SMC0:0"
  metadata_path: "meta/meta_SMC0.tsv"
}
embeddings {
  tensor_name: "TAS0:0"
  metadata_path: "meta/meta_TAS0.tsv"
}
embeddings {
  tensor_name: "RJB0:0"
  metadata_path: "meta/meta_RJB0.tsv"
}
embeddings {
  tensor_name: "UTB0:0"
  metadata_path: "meta/meta_UTB0.tsv"
}
embeddings {
  tensor_name: "PGH0:0"
  metadata_path: "meta/meta_PGH0.tsv"
}
embeddings {
  tensor_name: "RGM0:0"
  metadata_path: "meta/meta_RGM0.tsv"
}
embeddings {
  tensor_name: "RAB0:0"
  metadata_path: "meta/meta_RAB0.tsv"
}
embeddings {
  tensor_name: "JDA0:0"
  metadata_path: "meta/meta_JDA0.tsv"
}
embeddings {
  tensor_name: "AJC0:0"
  metadata_path: "meta/meta_AJC0.tsv"
}
embeddings {
  tensor_name: "CDD0:0"
  metadata_path: "meta/meta_CDD0.tsv"
}
embeddings {
  tensor_name: "CRE0:0"
  metadata_path: "meta/meta_CRE0.tsv"
}
embeddings {
  tensor_name: "KLS0:0"
  metadata_path: "meta/meta_KLS0.tsv"
}
embeddings {
  tensor_name: "TBC0:0"
  metadata_path: "meta/meta_TBC0.tsv"
}
embeddings {
  tensor_name: "RMB0:0"
  metadata_path: "meta/meta_RMB0.tsv"
}
embeddings {
  tensor_name: "SAH0:0"
  metadata_path: "meta/meta_SAH0.tsv"
}
embeddings {
  tensor_name: "JLN0:0"
  metadata_path: "meta/meta_JLN0.tsv"
}
embeddings {
  tensor_name: "GSL0:0"
  metadata_path: "meta/meta_GSL0.tsv"
}
embeddings {
  tensor_name: "DAW1:0"
  metadata_path: "meta/meta_DAW1.tsv"
}
embeddings {
  tensor_name: "RCS0:0"
  metadata_path: "meta/meta_RCS0.tsv"
}
embeddings {
  tensor_name: "MEA0:0"
  metadata_path: "meta/meta_MEA0.tsv"
}
embeddings {
  tensor_name: "MDM0:0"
  metadata_path: "meta/meta_MDM0.tsv"
}
embeddings {
  tensor_name: "CTH0:0"
  metadata_path: "meta/meta_CTH0.tsv"
}
embeddings {
  tensor_name: "KLH0:0"
  metadata_path: "meta/meta_KLH0.tsv"
}
embeddings {
  tensor_name: "TWH1:0"
  metadata_path: "meta/meta_TWH1.tsv"
}
embeddings {
  tensor_name: "DBB1:0"
  metadata_path: "meta/meta_DBB1.tsv"
}
embeddings {
  tensor_name: "JTH0:0"
  metadata_path: "meta/meta_JTH0.tsv"
}
embeddings {
  tensor_name: "MJR0:0"
  metadata_path: "meta/meta_MJR0.tsv"
}
embeddings {
  tensor_name: "JDG0:0"
  metadata_path: "meta/meta_JDG0.tsv"
}
embeddings {
  tensor_name: "DRD1:0"
  metadata_path: "meta/meta_DRD1.tsv"
}
embeddings {
  tensor_name: "BML0:0"
  metadata_path: "meta/meta_BML0.tsv"
}
embeddings {
  tensor_name: "MCC0:0"
  metadata_path: "meta/meta_MCC0.tsv"
}
embeddings {
  tensor_name: "RJR0:0"
  metadata_path: "meta/meta_RJR0.tsv"
}
embeddings {
  tensor_name: "LHD0:0"
  metadata_path: "meta/meta_LHD0.tsv"
}
embeddings {
  tensor_name: "KFB0:0"
  metadata_path: "meta/meta_KFB0.tsv"
}
embeddings {
  tensor_name: "KAM0:0"
  metadata_path: "meta/meta_KAM0.tsv"
}
embeddings {
  tensor_name: "CMH1:0"
  metadata_path: "meta/meta_CMH1.tsv"
}
embeddings {
  tensor_name: "GAK0:0"
  metadata_path: "meta/meta_GAK0.tsv"
}
embeddings {
  tensor_name: "AEM0:0"
  metadata_path: "meta/meta_AEM0.tsv"
}
embeddings {
  tensor_name: "JKR0:0"
  metadata_path: "meta/meta_JKR0.tsv"
}
embeddings {
  tensor_name: "EWM0:0"
  metadata_path: "meta/meta_EWM0.tsv"
}
embeddings {
  tensor_name: "DED0:0"
  metadata_path: "meta/meta_DED0.tsv"
}
embeddings {
  tensor_name: "DSJ0:0"
  metadata_path: "meta/meta_DSJ0.tsv"
}
embeddings {
  tensor_name: "RLJ1:0"
  metadata_path: "meta/meta_RLJ1.tsv"
}
embeddings {
  tensor_name: "PGR1:0"
  metadata_path: "meta/meta_PGR1.tsv"
}
embeddings {
  tensor_name: "JHK0:0"
  metadata_path: "meta/meta_JHK0.tsv"
}
embeddings {
  tensor_name: "PAB1:0"
  metadata_path: "meta/meta_PAB1.tsv"
}
embeddings {
  tensor_name: "MML0:0"
  metadata_path: "meta/meta_MML0.tsv"
}
embeddings {
  tensor_name: "RAM1:0"
  metadata_path: "meta/meta_RAM1.tsv"
}
embeddings {
  tensor_name: "ECD0:0"
  metadata_path: "meta/meta_ECD0.tsv"
}
embeddings {
  tensor_name: "DPK0:0"
  metadata_path: "meta/meta_DPK0.tsv"
}
embeddings {
  tensor_name: "MAF0:0"
  metadata_path: "meta/meta_MAF0.tsv"
}
embeddings {
  tensor_name: "RJH0:0"
  metadata_path: "meta/meta_RJH0.tsv"
}
embeddings {
  tensor_name: "JRG0:0"
  metadata_path: "meta/meta_JRG0.tsv"
}
embeddings {
  tensor_name: "JLR0:0"
  metadata_path: "meta/meta_JLR0.tsv"
}
embeddings {
  tensor_name: "DMT0:0"
  metadata_path: "meta/meta_DMT0.tsv"
}
embeddings {
  tensor_name: "DLR1:0"
  metadata_path: "meta/meta_DLR1.tsv"
}
embeddings {
  tensor_name: "TAS1:0"
  metadata_path: "meta/meta_TAS1.tsv"
}
embeddings {
  tensor_name: "SDB0:0"
  metadata_path: "meta/meta_SDB0.tsv"
}
embeddings {
  tensor_name: "BWP0:0"
  metadata_path: "meta/meta_BWP0.tsv"
}
embeddings {
  tensor_name: "BMA0:0"
  metadata_path: "meta/meta_BMA0.tsv"
}
embeddings {
  tensor_name: "NTW0:0"
  metadata_path: "meta/meta_NTW0.tsv"
}
embeddings {
  tensor_name: "JRK0:0"
  metadata_path: "meta/meta_JRK0.tsv"
}
embeddings {
  tensor_name: "SXA0:0"
  metadata_path: "meta/meta_SXA0.tsv"
}
embeddings {
  tensor_name: "FXV0:0"
  metadata_path: "meta/meta_FXV0.tsv"
}
embeddings {
  tensor_name: "CKE0:0"
  metadata_path: "meta/meta_CKE0.tsv"
}
embeddings {
  tensor_name: "WRE0:0"
  metadata_path: "meta/meta_WRE0.tsv"
}
embeddings {
  tensor_name: "AEO0:0"
  metadata_path: "meta/meta_AEO0.tsv"
}
embeddings {
  tensor_name: "TPP0:0"
  metadata_path: "meta/meta_TPP0.tsv"
}
embeddings {
  tensor_name: "CCS0:0"
  metadata_path: "meta/meta_CCS0.tsv"
}
embeddings {
  tensor_name: "KAA0:0"
  metadata_path: "meta/meta_KAA0.tsv"
}
embeddings {
  tensor_name: "SFH1:0"
  metadata_path: "meta/meta_SFH1.tsv"
}
embeddings {
  tensor_name: "DLC0:0"
  metadata_path: "meta/meta_DLC0.tsv"
}
embeddings {
  tensor_name: "NLS0:0"
  metadata_path: "meta/meta_NLS0.tsv"
}
embeddings {
  tensor_name: "BTH0:0"
  metadata_path: "meta/meta_BTH0.tsv"
}
embeddings {
  tensor_name: "TJG0:0"
  metadata_path: "meta/meta_TJG0.tsv"
}
embeddings {
  tensor_name: "JSA0:0"
  metadata_path: "meta/meta_JSA0.tsv"
}
embeddings {
  tensor_name: "MGC0:0"
  metadata_path: "meta/meta_MGC0.tsv"
}
embeddings {
  tensor_name: "FER0:0"
  metadata_path: "meta/meta_FER0.tsv"
}
embeddings {
  tensor_name: "SJK1:0"
  metadata_path: "meta/meta_SJK1.tsv"
}
embeddings {
  tensor_name: "LIH0:0"
  metadata_path: "meta/meta_LIH0.tsv"
}
embeddings {
  tensor_name: "PDF0:0"
  metadata_path: "meta/meta_PDF0.tsv"
}
embeddings {
  tensor_name: "DBP0:0"
  metadata_path: "meta/meta_DBP0.tsv"
}
embeddings {
  tensor_name: "SMA0:0"
  metadata_path: "meta/meta_SMA0.tsv"
}
embeddings {
  tensor_name: "WAD0:0"
  metadata_path: "meta/meta_WAD0.tsv"
}
embeddings {
  tensor_name: "REW0:0"
  metadata_path: "meta/meta_REW0.tsv"
}
embeddings {
  tensor_name: "DRM0:0"
  metadata_path: "meta/meta_DRM0.tsv"
}
embeddings {
  tensor_name: "REE0:0"
  metadata_path: "meta/meta_REE0.tsv"
}
embeddings {
  tensor_name: "DCD0:0"
  metadata_path: "meta/meta_DCD0.tsv"
}
embeddings {
  tensor_name: "RDM0:0"
  metadata_path: "meta/meta_RDM0.tsv"
}
embeddings {
  tensor_name: "TMR0:0"
  metadata_path: "meta/meta_TMR0.tsv"
}
embeddings {
  tensor_name: "RJM0:0"
  metadata_path: "meta/meta_RJM0.tsv"
}
embeddings {
  tensor_name: "GDP0:0"
  metadata_path: "meta/meta_GDP0.tsv"
}
embeddings {
  tensor_name: "THC0:0"
  metadata_path: "meta/meta_THC0.tsv"
}
embeddings {
  tensor_name: "DNC0:0"
  metadata_path: "meta/meta_DNC0.tsv"
}
embeddings {
  tensor_name: "DLC1:0"
  metadata_path: "meta/meta_DLC1.tsv"
}
embeddings {
  tensor_name: "BJL0:0"
  metadata_path: "meta/meta_BJL0.tsv"
}
embeddings {
  tensor_name: "MAB0:0"
  metadata_path: "meta/meta_MAB0.tsv"
}
embeddings {
  tensor_name: "SKL0:0"
  metadata_path: "meta/meta_SKL0.tsv"
}
embeddings {
  tensor_name: "JEN0:0"
  metadata_path: "meta/meta_JEN0.tsv"
}
embeddings {
  tensor_name: "LOD0:0"
  metadata_path: "meta/meta_LOD0.tsv"
}
embeddings {
  tensor_name: "MSM0:0"
  metadata_path: "meta/meta_MSM0.tsv"
}
embeddings {
  tensor_name: "LEH0:0"
  metadata_path: "meta/meta_LEH0.tsv"
}
embeddings {
  tensor_name: "AKB0:0"
  metadata_path: "meta/meta_AKB0.tsv"
}
embeddings {
  tensor_name: "RPP0:0"
  metadata_path: "meta/meta_RPP0.tsv"
}
embeddings {
  tensor_name: "TPF0:0"
  metadata_path: "meta/meta_TPF0.tsv"
}
embeddings {
  tensor_name: "LJD0:0"
  metadata_path: "meta/meta_LJD0.tsv"
}
embeddings {
  tensor_name: "ERS0:0"
  metadata_path: "meta/meta_ERS0.tsv"
}
embeddings {
  tensor_name: "RSO0:0"
  metadata_path: "meta/meta_RSO0.tsv"
}
embeddings {
  tensor_name: "ZMB0:0"
  metadata_path: "meta/meta_ZMB0.tsv"
}
embeddings {
  tensor_name: "CRH0:0"
  metadata_path: "meta/meta_CRH0.tsv"
}
embeddings {
  tensor_name: "RLR0:0"
  metadata_path: "meta/meta_RLR0.tsv"
}
embeddings {
  tensor_name: "SGF0:0"
  metadata_path: "meta/meta_SGF0.tsv"
}
embeddings {
  tensor_name: "RCG0:0"
  metadata_path: "meta/meta_RCG0.tsv"
}
embeddings {
  tensor_name: "MRP0:0"
  metadata_path: "meta/meta_MRP0.tsv"
}
embeddings {
  tensor_name: "MWS1:0"
  metadata_path: "meta/meta_MWS1.tsv"
}
embeddings {
  tensor_name: "KKH0:0"
  metadata_path: "meta/meta_KKH0.tsv"
}
embeddings {
  tensor_name: "NJM0:0"
  metadata_path: "meta/meta_NJM0.tsv"
}
embeddings {
  tensor_name: "RJM4:0"
  metadata_path: "meta/meta_RJM4.tsv"
}
embeddings {
  tensor_name: "EJL0:0"
  metadata_path: "meta/meta_EJL0.tsv"
}
embeddings {
  tensor_name: "RWA0:0"
  metadata_path: "meta/meta_RWA0.tsv"
}
